Fix/sentence quality
rahmansahinler1/ragchat_local pull request #39
Opened 2024-09-21 08:57 UTC by ozgurnsahin

Created _process_regex function to further improve sentence quality of the extracted regex

2024-09-21 17:24 UTC, rahmansahinler1 commented on functions/reading_functions.py
> +    # #query spell handler
Delete commented out code

2024-09-21 17:26 UTC, rahmansahinler1 commented
1- change resource branch from main to develop
2- add yourself as assignee
3- attach label
4- attach project

2024-09-23 10:51 UTC, rahmansahinler1 requested changes

2024-09-23 10:51 UTC, rahmansahinler1 commented on .gitignore
> +# pdf files
No need explanation here. Just file is enough

2024-09-23 10:51 UTC, rahmansahinler1 commented on .gitignore
> +#jupyter notabooks
JUPYTER NOTABOOKS!!

2024-10-24 19:58 UTC, rahmansahinler1 commented
eski oldugu icin kapatiyorum guncel mr bu kisimlari kapsiyor sanirim

2024-10-24 19:58 UTC, closed without merging

2024-10-24 20:17 UTC, ozgurnsahin commented
Kapsıyor bunu eklemiştik diğer pull requestlere